
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/fully_connected.ipynb

from exp.nb_matmul import *
import torch.nn
import math

def normalize(x, mean, std): return (x - mean)/std

def test_near_zero(x): assert x < 1e-3

from torch.nn import init

def print_stats(x):
    print(x.mean(),x.std())

def mse(pred, true): return(pred.squeeze(-1)-true).pow(2).mean()

def test_near(a,b): return torch.allclose(a,b, rtol=1e-3)